/* Textos das páginas legais, nas duas línguas.
   `h` = subtítulo, `p` = parágrafo, `ul` = lista, `nota` = caixa destacada. */

export const legal = {
  pt: {
    privacidade: {
      titulo: 'Política de Privacidade',
      descricao:
        'Como a Clínica Dentária S. Dâmaso trata os seus dados pessoais. Este site não recolhe dados nem utiliza cookies de rastreio.',
      blocos: [
        { nota: 'este site é meramente informativo. Não tem formulários, não utiliza ferramentas de estatística e não recolhe quaisquer dados pessoais enquanto o consulta.' },
        { h: '1. Quem é o responsável pelo tratamento' },
        { p: 'A Clínica Dentária S. Dâmaso, com morada na Alameda S. Dâmaso 23, 4810-286 Guimarães, é a responsável pelo tratamento dos dados pessoais referidos nesta política. Para qualquer questão relacionada com privacidade, pode contactar-nos através do e-mail {email} ou do telefone {telefone}.' },
        { h: '2. Que dados recolhemos através do site' },
        { p: 'Nenhuns. Este site não possui formulários de contacto ou de marcação, não utiliza ferramentas de analítica e não cria perfis de navegação. A navegação é anónima do nosso lado.' },
        { p: 'Como acontece em qualquer alojamento web, o servidor que aloja o site pode registar dados técnicos de acesso — como o endereço IP, a data e hora do pedido e o tipo de navegador — exclusivamente para garantir a segurança e o funcionamento do serviço. Esses registos são geridos pelo fornecedor de alojamento e não são usados por nós para o identificar.' },
        { h: '3. Quando nos contacta' },
        { p: 'Se nos contactar por telefone, WhatsApp ou e-mail, trataremos os dados que nos fornecer (nome, contacto e o conteúdo da mensagem) apenas para lhe responder e, se for caso disso, agendar uma consulta. A base legal é o nosso interesse legítimo em responder a quem nos procura e, quando aplicável, a execução de diligências pré-contratuais a seu pedido.' },
        { h: '4. Dados clínicos' },
        { p: 'Os dados de saúde recolhidos no âmbito da prestação de cuidados são tratados fora deste site, em sistemas próprios da clínica, estão sujeitos a sigilo profissional e são conservados pelos prazos legalmente exigidos. O seu tratamento assenta na alínea h) do n.º 2 do artigo 9.º do Regulamento Geral sobre a Proteção de Dados, relativa à prestação de cuidados de saúde.' },
        { h: '5. Partilha com terceiros' },
        { p: 'Não vendemos nem cedemos dados pessoais a terceiros. Os dados só podem ser comunicados a entidades subcontratadas necessárias ao funcionamento da clínica ou a autoridades públicas, quando a lei o exija.' },
        { h: '6. Conteúdos externos' },
        { p: 'A página de contactos inclui um mapa do Google Maps que <strong>só é carregado depois de o clicar</strong>. Enquanto não o fizer, nenhum pedido é enviado ao Google. Ao carregá-lo, o Google poderá recolher dados e instalar cookies, nos termos da política de privacidade do próprio Google. Ver a {ligacaoCookies}.' },
        { h: '7. Os seus direitos' },
        { p: 'Nos termos do RGPD, pode a qualquer momento solicitar:' },
        { ul: ['o acesso aos dados pessoais que tratamos a seu respeito;', 'a retificação de dados incorretos ou incompletos;', 'o apagamento dos dados, quando não exista obrigação legal de os conservar;', 'a limitação ou a oposição ao tratamento;', 'a portabilidade dos dados.'] },
        { p: 'Para exercer estes direitos, contacte-nos pelos meios indicados no ponto 1. Caso considere que os seus direitos não foram respeitados, pode apresentar reclamação junto da Comissão Nacional de Proteção de Dados (<a href="https://www.cnpd.pt" target="_blank" rel="noopener noreferrer">cnpd.pt</a>).' },
        { h: '8. Alterações a esta política' },
        { p: 'Esta política pode ser atualizada sempre que se justifique. A data da última atualização encontra-se no topo da página.' },
      ],
    },
    cookies: {
      titulo: 'Política de Cookies',
      descricao: 'Este site não instala cookies. O mapa do Google Maps só é carregado mediante ação explícita do visitante.',
      blocos: [
        { nota: 'este site não instala cookies no seu dispositivo. Não usamos cookies de estatística nem de publicidade, por isso não encontrará aqui qualquer janela de consentimento.' },
        { h: '1. O que são cookies' },
        { p: 'Os cookies são pequenos ficheiros de texto que um site guarda no seu computador ou telemóvel para recordar informação entre visitas — por exemplo, preferências de idioma ou dados de sessão.' },
        { h: '2. Cookies utilizados por este site' },
        { p: 'Nenhum. O site é constituído por páginas estáticas e não guarda cookies próprios, não utiliza Google Analytics ou ferramentas equivalentes, e não integra pixéis de redes sociais ou de publicidade.' },
        { h: '3. Mapa do Google Maps' },
        { p: 'A secção de contactos inclui um mapa fornecido pelo Google. Para proteger a sua privacidade, esse mapa <strong>não é carregado automaticamente</strong>: em vez dele é apresentado um aviso com um botão. O pedido ao Google só é feito se, e quando, escolher carregar o mapa.' },
        { p: 'A partir desse momento, o Google poderá instalar cookies e recolher dados de utilização, de acordo com as suas próprias regras. Pode consultá-las na <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">política de privacidade do Google</a>. Basta recarregar a página para voltar ao estado inicial, sem mapa.' },
        { h: '4. Como gerir cookies no seu navegador' },
        { p: 'Independentemente deste site, pode a qualquer momento bloquear ou eliminar cookies nas definições do seu navegador. Os menus de ajuda do Chrome, Safari, Firefox e Edge explicam o procedimento para cada um. Tenha em conta que bloquear cookies pode afetar o funcionamento de outros sites.' },
        { h: '5. Alterações a esta política' },
        { p: 'Se no futuro passarmos a utilizar cookies — por exemplo, para medir visitas —, esta página será atualizada e passará a ser pedido o seu consentimento prévio.' },
      ],
    },
    termos: {
      titulo: 'Termos e Condições',
      descricao: 'Condições de utilização do site da Clínica Dentária S. Dâmaso, em Guimarães.',
      blocos: [
        { h: '1. Objeto' },
        { p: 'Os presentes termos regulam o acesso e a utilização do site da Clínica Dentária S. Dâmaso. Ao navegar neste site, está a aceitá-los. Se não concordar com algum ponto, deve abster-se de o utilizar.' },
        { h: '2. Natureza da informação' },
        { p: 'O conteúdo deste site tem finalidade exclusivamente informativa sobre a clínica, a sua equipa e as áreas de medicina dentária que pratica.' },
        { nota: 'A informação aqui apresentada <strong>não constitui aconselhamento clínico nem substitui uma consulta</strong>. Qualquer diagnóstico ou plano de tratamento exige observação presencial por um médico dentista.', semPrefixo: true },
        { h: '3. Marcações' },
        { p: 'Este site não permite efetuar marcações em linha. As consultas são agendadas por telefone, WhatsApp ou e-mail, e só se consideram confirmadas após resposta da clínica.' },
        { h: '4. Propriedade intelectual' },
        { p: 'Os textos, o logótipo, as fotografias da equipa e os restantes elementos gráficos deste site são propriedade da Clínica Dentária S. Dâmaso ou dos respetivos titulares, e estão protegidos por lei. Não é permitida a sua reprodução, distribuição ou modificação sem autorização prévia por escrito, salvo para uso pessoal e não comercial.' },
        { h: '5. Ligações para sites terceiros' },
        { p: 'Este site contém ligações para sites externos, nomeadamente o Google Maps, o Livro de Reclamações Eletrónico e a entidade responsável pela distinção PME apresentada. Não controlamos esses sites nem somos responsáveis pelos seus conteúdos ou políticas de privacidade.' },
        { h: '6. Disponibilidade e responsabilidade' },
        { p: 'Procuramos manter a informação correta e atualizada, mas não garantimos que esteja isenta de imprecisões nem que o site esteja permanentemente disponível. Na medida permitida por lei, a clínica não se responsabiliza por danos resultantes da utilização ou da impossibilidade de utilização deste site.' },
        { h: '7. Reclamações e resolução de litígios' },
        { p: 'Pode apresentar reclamação através do <a href="https://www.livroreclamacoes.pt" target="_blank" rel="noopener noreferrer">Livro de Reclamações Eletrónico</a>. Em caso de litígio de consumo, o consumidor pode recorrer a uma entidade de resolução alternativa de litígios, nos termos da Lei n.º 144/2015, de 8 de setembro.' },
        { comentario: 'A LEI 144/2015 EXIGE INDICAR A ENTIDADE RAL COMPETENTE. Inserir aqui o nome e o sítio da entidade a que a clínica está vinculada.' },
        { h: '8. Lei aplicável' },
        { p: 'Estes termos regem-se pela lei portuguesa. Para a resolução de qualquer litígio é competente o foro da comarca de Guimarães, com renúncia expressa a qualquer outro, salvo disposição legal imperativa em contrário.' },
      ],
    },
  },

  en: {
    privacidade: {
      titulo: 'Privacy Policy',
      descricao:
        'How S. Dâmaso Dental Practice handles your personal data. This website collects no data and uses no tracking cookies.',
      blocos: [
        { nota: 'this website is purely informational. It has no forms, uses no analytics tools and collects no personal data while you browse it.' },
        { h: '1. Who is the data controller' },
        { p: 'S. Dâmaso Dental Practice, of Alameda S. Dâmaso 23, 4810-286 Guimarães, Portugal, is the controller of the personal data referred to in this policy. For any privacy-related question, you can contact us at {email} or on {telefone}.' },
        { h: '2. What data we collect through the website' },
        { p: 'None. This website has no contact or booking forms, uses no analytics tools and builds no browsing profiles. From our side, your visit is anonymous.' },
        { p: 'As with any web hosting, the server hosting the site may log technical access data — such as the IP address, the date and time of the request and the browser type — solely to keep the service secure and working. Those logs are managed by the hosting provider and are not used by us to identify you.' },
        { h: '3. When you contact us' },
        { p: 'If you contact us by telephone, WhatsApp or email, we will process the data you give us (name, contact details and the content of your message) only in order to reply and, where appropriate, to arrange an appointment. The legal basis is our legitimate interest in responding to enquiries and, where applicable, taking steps at your request prior to entering into a contract.' },
        { h: '4. Clinical data' },
        { p: 'Health data collected in the course of providing care is processed outside this website, in the practice’s own systems. It is subject to professional confidentiality and retained for the periods required by law. Its processing rests on Article 9(2)(h) of the General Data Protection Regulation, concerning the provision of health care.' },
        { h: '5. Sharing with third parties' },
        { p: 'We do not sell or pass on personal data to third parties. Data may only be disclosed to processors necessary for running the practice, or to public authorities where the law requires it.' },
        { h: '6. External content' },
        { p: 'The contact section includes a Google Maps map that <strong>is only loaded once you click</strong>. Until you do, no request is sent to Google. Once loaded, Google may collect data and place cookies, under Google’s own privacy policy. See the {ligacaoCookies}.' },
        { h: '7. Your rights' },
        { p: 'Under the GDPR, you may at any time request:' },
        { ul: ['access to the personal data we hold about you;', 'rectification of inaccurate or incomplete data;', 'erasure of the data, where no legal obligation requires us to keep it;', 'restriction of, or objection to, the processing;', 'portability of the data.'] },
        { p: 'To exercise these rights, contact us using the details in section 1. If you believe your rights have not been respected, you may lodge a complaint with the Portuguese data protection authority, the Comissão Nacional de Proteção de Dados (<a href="https://www.cnpd.pt" target="_blank" rel="noopener noreferrer">cnpd.pt</a>).' },
        { h: '8. Changes to this policy' },
        { p: 'This policy may be updated whenever necessary. The date of the last update appears at the top of the page.' },
      ],
    },
    cookies: {
      titulo: 'Cookie Policy',
      descricao: 'This website sets no cookies. The Google Maps map is only loaded if the visitor explicitly asks for it.',
      blocos: [
        { nota: 'this website places no cookies on your device. We use no analytics or advertising cookies, which is why you will not find a consent banner here.' },
        { h: '1. What cookies are' },
        { p: 'Cookies are small text files that a website stores on your computer or phone to remember information between visits — language preferences or session data, for example.' },
        { h: '2. Cookies used by this website' },
        { p: 'None. The site is made up of static pages and stores no cookies of its own. It does not use Google Analytics or equivalent tools, and includes no social media or advertising pixels.' },
        { h: '3. The Google Maps map' },
        { p: 'The contact section includes a map provided by Google. To protect your privacy, that map <strong>is not loaded automatically</strong>: a notice with a button is shown instead. The request to Google is only made if and when you choose to load the map.' },
        { p: 'From that point, Google may place cookies and collect usage data, under its own rules. You can read them in <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">Google’s privacy policy</a>. Simply reload the page to return to the initial state, with no map.' },
        { h: '4. Managing cookies in your browser' },
        { p: 'Regardless of this site, you can block or delete cookies at any time in your browser settings. The help menus in Chrome, Safari, Firefox and Edge explain how for each. Bear in mind that blocking cookies may affect how other websites work.' },
        { h: '5. Changes to this policy' },
        { p: 'If we start using cookies in future — to measure visits, for instance — this page will be updated and your prior consent will be requested.' },
      ],
    },
    termos: {
      titulo: 'Terms and Conditions',
      descricao: 'Terms of use for the S. Dâmaso Dental Practice website, in Guimarães, Portugal.',
      blocos: [
        { h: '1. Scope' },
        { p: 'These terms govern access to and use of the S. Dâmaso Dental Practice website. By browsing this site you accept them. If you disagree with any point, please do not use the site.' },
        { h: '2. Nature of the information' },
        { p: 'The content of this site is provided purely for information about the practice, its team and the areas of dentistry it covers.' },
        { nota: 'The information presented here <strong>does not constitute clinical advice and is no substitute for an appointment</strong>. Any diagnosis or treatment plan requires an in-person examination by a dentist.', semPrefixo: true },
        { h: '3. Appointments' },
        { p: 'This site does not allow online booking. Appointments are arranged by telephone, WhatsApp or email, and are only confirmed once the practice has replied.' },
        { h: '4. Intellectual property' },
        { p: 'The text, logo, team photographs and other graphic elements on this site belong to S. Dâmaso Dental Practice or to their respective owners, and are protected by law. They may not be reproduced, distributed or modified without prior written permission, except for personal, non-commercial use.' },
        { h: '5. Links to third-party sites' },
        { p: 'This site contains links to external sites, namely Google Maps, the Portuguese Electronic Complaints Book and the body responsible for the SME distinction shown. We do not control those sites and are not responsible for their content or privacy policies.' },
        { h: '6. Availability and liability' },
        { p: 'We aim to keep the information accurate and up to date, but we do not guarantee that it is free of inaccuracies, nor that the site will be permanently available. To the extent permitted by law, the practice accepts no liability for damage arising from the use of, or inability to use, this site.' },
        { h: '7. Complaints and dispute resolution' },
        { p: 'You may submit a complaint through the <a href="https://www.livroreclamacoes.pt" target="_blank" rel="noopener noreferrer">Portuguese Electronic Complaints Book</a>. In the event of a consumer dispute, consumers may refer the matter to an alternative dispute resolution body, under Portuguese Law 144/2015 of 8 September.' },
        { comentario: 'LAW 144/2015 REQUIRES NAMING THE COMPETENT ADR BODY. Insert here the name and website of the body the practice is registered with.' },
        { h: '8. Governing law' },
        { p: 'These terms are governed by Portuguese law. Any dispute shall be submitted to the courts of the district of Guimarães, to the exclusion of any other, save where mandatory legal provisions state otherwise.' },
      ],
    },
  },
};
